/*
 * testSuiteFiles.js - list the test files in this directory
 * 
 * Copyright © 2017-2018, 2020 JEDLSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports.files = [
    "testclock.js",
    "testcalendar.js",
    "testdate.js",
    "testdateasync.js",
    "testdatefmt.js",
    "testdatetimefmt.js",
    "testdatefmtasync.js",
    "testDayOfWeek.js",
    "testMeridiems.js",
    "testMonthTranslation.js",
    "testWeekdayTranslation.js",
    "testdatefmt_af_NA.js",
    "testdatefmt_af_ZA.js",
    "testdatefmt_am_ET.js",
    "testdatefmt_ar_EG.js",
    "testdatefmt_ar_SA.js",
    "testdatefmt_as_IN.js",
    "testdatefmt_az_Latn_AZ.js",
    "testdatefmt_be_BY.js",
    "testdatefmt_bg.js",
    "testdatefmt_bn_IN.js",
    "testdatefmt_bs_Cyrl_BA.js",
    "testdatefmt_bs_Latn_BA.js",
    "testdatefmt_ca.js",
    "testdatefmt_cop_EG.js",
    "testdatefmt_cs_CZ.js",
    "testdatefmt_da_DK.js",
    "testdatefmt_de_DE.js",
    "testdatefmt_el_GR.js",
    "testdatefmt_en_CA.js",
    "testdatefmt_en_GB.js",
    "testdatefmt_en_IN.js",
    "testdatefmt_en_US.js",
    "testdatefmt_es_CO.js",
    "testdatefmt_es_ES.js",
    "testdatefmt_et_EE.js",
    "testdatefmt_eu_ES.js",
    "testdatefmt_fa_IR.js",
    "testdatefmt_fi_FI.js",
    "testdatefmt_fr_CA.js",
    "testdatefmt_fr_FR.js",
    "testdatefmt_ga_IE.js",
    "testdatefmt_gl_ES.js",
    "testdatefmt_gu_IN.js",
    "testdatefmt_ha_Latn_NG.js",
    "testdatefmt_he_IL.js",
    "testdatefmt_hi_IN.js",
    "testdatefmt_hr_HR.js",
    "testdatefmt_hy_AM.js",
    "testdatefmt_id_ID.js",
    "testdatefmt_it_IT.js",
    "testdatefmt_ja_JP.js",
    "testdatefmt_ka_GE.js",
    "testdatefmt_kk_Cyrl_KZ.js",
    "testdatefmt_km_KH.js",
    "testdatefmt_kn_IN.js",
    "testdatefmt_ko_KR.js",
    "testdatefmt_ku_Arab_IQ.js",
    "testdatefmt_ky_KG.js",
    "testdatefmt_lo_LA.js",
    "testdatefmt_lt_LT.js",
    "testdatefmt_lv_LV.js",
    "testdatefmt_mk_MK.js",
    "testdatefmt_ml_IN.js",
    "testdatefmt_mn_Cyrl_MN.js",
    "testdatefmt_mr_IN.js",
    "testdatefmt_ms_MY.js",
    "testdatefmt_my_MM.js",
    "testdatefmt_nb_NO.js",
    "testdatefmt_ne_NP.js",
    "testdatefmt_nl_NL.js",
    "testdatefmt_or_IN.js",
    "testdatefmt_pa_IN.js",
    "testdatefmt_pl_PL.js",
    "testdatefmt_pt_BR.js",
    "testdatefmt_ro_RO.js",
    "testdatefmt_ru_RU.js",
    "testdatefmt_si_LK.js",
    "testdatefmt_sk_SK.js",
    "testdatefmt_sl_SI.js",
    "testdatefmt_sq_AL.js",
    "testdatefmt_sr_Latn_RS.js",
    "testdatefmt_sv_SE.js",
    "testdatefmt_sw_KE.js",
    "testdatefmt_ta_IN.js",
    "testdatefmt_te_IN.js",
    "testdatefmt_th_TH.js",
    "testdatefmt_tr_TR.js",
    "testdatefmt_uk_UA.js",
    "testdatefmt_ur_IN.js",
    "testdatefmt_uz_Cyrl_UZ.js",
    "testdatefmt_uz_Latn_UZ.js",
    "testdatefmt_vi_VN.js",
    "testdatefmt_zh_CN.js",
    "testdatefmt_zh_Hant_HK.js",
    "testdatefmt_zh_Hant_TW.js"
];