/*
 * testSuiteQml.js - test suite for this directory
 * 
 * Copyright © 2018, JEDLSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports.address = {
    "testaddress": "testaddress.js",
    "testaddress_AE": "testaddress_AE.js",
    "testaddress_AF": "testaddress_AF.js",
    "testaddress_AL": "testaddress_AL.js",
    "testaddress_AM": "testaddress_AM.js",
    "testaddress_AO": "testaddress_AO.js",
    "testaddress_AR": "testaddress_AR.js",
    "testaddress_AT": "testaddress_AT.js",
    "testaddress_AU": "testaddress_AU.js",
    "testaddress_AZ": "testaddress_AZ.js",
    "testaddress_BA": "testaddress_BA.js",
    "testaddress_BE": "testaddress_BE.js",
    "testaddress_BF": "testaddress_BF.js",
    "testaddress_BG": "testaddress_BG.js",
    "testaddress_BH": "testaddress_BH.js",
    "testaddress_BJ": "testaddress_BJ.js",
    "testaddress_BO": "testaddress_BO.js",
    "testaddress_BR": "testaddress_BR.js",
    "testaddress_BY": "testaddress_BY.js",
    "testaddress_CA": "testaddress_CA.js",
    "testaddress_CD": "testaddress_CD.js",
    "testaddress_CF": "testaddress_CF.js",
    "testaddress_CG": "testaddress_CG.js",
    "testaddress_CH": "testaddress_CH.js",
    "testaddress_CI": "testaddress_CI.js",
    "testaddress_CL": "testaddress_CL.js",
    "testaddress_CM": "testaddress_CM.js",
    "testaddress_CN": "testaddress_CN.js",
    "testaddress_CO": "testaddress_CO.js",
    "testaddress_CR": "testaddress_CR.js",
    "testaddress_CV": "testaddress_CV.js",
    "testaddress_CZ": "testaddress_CZ.js",
    "testaddress_DE": "testaddress_DE.js",
    "testaddress_DJ": "testaddress_DJ.js",
    "testaddress_DK": "testaddress_DK.js",
    "testaddress_DO": "testaddress_DO.js",
    "testaddress_DZ": "testaddress_DZ.js",
    "testaddress_EC": "testaddress_EC.js",
    "testaddress_EE": "testaddress_EE.js",
    "testaddress_EG": "testaddress_EG.js",
    "testaddress_ES": "testaddress_ES.js",
    "testaddress_ET": "testaddress_ET.js",
    "testaddress_FI": "testaddress_FI.js",
    "testaddress_FR": "testaddress_FR.js",
    "testaddress_GA": "testaddress_GA.js",
    "testaddress_GB": "testaddress_GB.js",
    "testaddress_GE": "testaddress_GE.js",
    "testaddress_GH": "testaddress_GH.js",
    "testaddress_GM": "testaddress_GM.js",
    "testaddress_GN": "testaddress_GN.js",
    "testaddress_GQ": "testaddress_GQ.js",
    "testaddress_GR": "testaddress_GR.js",
    "testaddress_GT": "testaddress_GT.js",
    "testaddress_HK": "testaddress_HK.js",
    "testaddress_HN": "testaddress_HN.js",
    "testaddress_HR": "testaddress_HR.js",
    "testaddress_HU": "testaddress_HU.js",
    "testaddress_ID": "testaddress_ID.js",
    "testaddress_IE": "testaddress_IE.js",
    "testaddress_IL": "testaddress_IL.js",
    "testaddress_IN": "testaddress_IN.js",
    "testaddress_IQ": "testaddress_IQ.js",
    "testaddress_IR": "testaddress_IR.js",
    "testaddress_IS": "testaddress_IS.js",
    "testaddress_IT": "testaddress_IT.js",
    "testaddress_JO": "testaddress_JO.js",
    "testaddress_JP": "testaddress_JP.js",
    "testaddress_KE": "testaddress_KE.js",
    "testaddress_KG": "testaddress_KG.js",
    "testaddress_KR": "testaddress_KR.js",
    "testaddress_KW": "testaddress_KW.js",
    "testaddress_LB": "testaddress_LB.js",
    "testaddress_LK": "testaddress_LK.js",
    "testaddress_LR": "testaddress_LR.js",
    "testaddress_LT": "testaddress_LT.js",
    "testaddress_LU": "testaddress_LU.js",
    "testaddress_LV": "testaddress_LV.js",
    "testaddress_LY": "testaddress_LY.js",
    "testaddress_MA": "testaddress_MA.js",
    "testaddress_ME": "testaddress_ME.js",
    "testaddress_MK": "testaddress_MK.js",
    "testaddress_ML": "testaddress_ML.js",
    "testaddress_MM": "testaddress_MM.js",
    "testaddress_MO": "testaddress_MO.js",
    "testaddress_MR": "testaddress_MR.js",
    "testaddress_MW": "testaddress_MW.js",
    "testaddress_MX": "testaddress_MX.js",
    "testaddress_MY": "testaddress_MY.js",
    "testaddress_NG": "testaddress_NG.js",
    "testaddress_NI": "testaddress_NI.js",
    "testaddress_NL": "testaddress_NL.js",
    "testaddress_NO": "testaddress_NO.js",
    "testaddress_NZ": "testaddress_NZ.js",
    "testaddress_OM": "testaddress_OM.js",
    "testaddress_PA": "testaddress_PA.js",
    "testaddress_PE": "testaddress_PE.js",
    "testaddress_PH": "testaddress_PH.js",
    "testaddress_PK": "testaddress_PK.js",
    "testaddress_PL": "testaddress_PL.js",
    "testaddress_PR": "testaddress_PR.js",
    "testaddress_PT": "testaddress_PT.js",
    "testaddress_PY": "testaddress_PY.js",
    "testaddress_QA": "testaddress_QA.js",
    "testaddress_RO": "testaddress_RO.js",
    "testaddress_RS": "testaddress_RS.js",
    "testaddress_RU": "testaddress_RU.js",
    "testaddress_RW": "testaddress_RW.js",
    "testaddress_SA": "testaddress_SA.js",
    "testaddress_SD": "testaddress_SD.js",
    "testaddress_SE": "testaddress_SE.js",
    "testaddress_SG": "testaddress_SG.js",
    "testaddress_SI": "testaddress_SI.js",
    "testaddress_SK": "testaddress_SK.js",
    "testaddress_SL": "testaddress_SL.js",
    "testaddress_SN": "testaddress_SN.js",
    "testaddress_SV": "testaddress_SV.js",
    "testaddress_SY": "testaddress_SY.js",
    "testaddress_TG": "testaddress_TG.js",
    "testaddress_TH": "testaddress_TH.js",
    "testaddress_TN": "testaddress_TN.js",
    "testaddress_TR": "testaddress_TR.js",
    "testaddress_TW": "testaddress_TW.js",
    "testaddress_TZ": "testaddress_TZ.js",
    "testaddress_UA": "testaddress_UA.js",
    "testaddress_UG": "testaddress_UG.js",
    "testaddress_UY": "testaddress_UY.js",
    "testaddress_VE": "testaddress_VE.js",
    "testaddress_VN": "testaddress_VN.js",
    "testaddress_YE": "testaddress_YE.js",
    "testaddress_ZA": "testaddress_ZA.js",
    "testaddress_ZM": "testaddress_ZM.js",
    "testaddress_ZM": "testaddressasync.js"
}
